name: zergiocunha_net
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate_on_scroll: ^0.3.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/cv/Profile.pdf
