name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
      - development
      - qas

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build web
      - name: Build web
        run: flutter build web

      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZERGIOCUNHA_DEV }}
          projectId: zergiocunha-dev
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Deploy to Firebase Hosting (Development)
        if: github.ref == 'refs/heads/development'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZERGIOCUNHA_DEV }}
          projectId: zergiocunha-dev
          channelId: dev
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Deploy to Firebase Hosting (QAS)
        if: github.ref == 'refs/heads/qas'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZERGIOCUNHA_DEV }}
          projectId: zergiocunha-dev
          channelId: qas
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks